- name: Listen for storage-monitor events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
    - name: http servers
      ansible.eda.url_check:
        delay: 10
        urls:
          # - http://IP:8000/eda.txt
          - "{{ eda_txt_url }}"

  rules:
    - name: list users - webhook
      condition: event.meta.headers is defined
      action:
        run_job_template:
          name: vm-list-users
          organization: jcorg

    - name: Wait VM IP
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: hc3-wait-vm-ip
          organization: jcorg
          job_args:
            extra_vars:
               # vm_name: "{{ vm_name }}"  # not passed to AAP job
               vm_name: no-such-vm  # not passed to AAP job
               # related to https://github.com/ansible/ansible-rulebook/issues/622 ?
               # Setting the 'prompt on run' in AAP helps, even if #622 says it does not apply.
