- name: Listen for storage-monitor events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Rule - Print event information
      condition: event.meta.headers is defined
      action:
        run_job_template:
          name: vm-list-users
          organization: jcorg
          job_args:
            extra_vars:
               vm_name: jc-ub2004-b
